### PR TITLE
fix: removes the object when editing hex inputs of the color picker. (fix #504)

### LINKED ISSUE #504: Pressing backspace key in hex color picker deletes the selected shape instead of hex code text
**Describe the bug**
When editing the color of a shape, the color picker shows the hex code of the current color and the user is able to edit that text string to get the color they want. However, if the user presses the backspace key to delete part of the string, the shape is deleted instead.

**To Reproduce**

1. Add a shape
2. Click on Stroke to open color picker
3. Click on hex code string to edit
4. Press backspace key
5. Notice shape is deleted and hex code string remains unchanged. Pressing the backspace key again edits the string as expected.

**Expected behavior**
Backspace key would delete characters in the hex code string, where the text cursor is located. Shape should not be deleted.

**Screenshots**
color-edit-delete-issue

**Desktop (please complete the following information):**

- OS: Windows
- Browser: Chrome
- Version: 87.0.4280.88

**Additional context**
This can be reproduced using the image editor on https://ui.toast.com/tui-image-editor

### PR DESCRIPTION
**Pull request by lja1018**
### Please check if the PR fulfills these requirements

- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [ ] It does not introduce a breaking change or has description for the breaking change

### Description

Fixed a bug that removed the object when editing the hex input of the color picker.

* AS-IS
  * asis
* TO-BE
  * Object is not removed, only the input box is modified.

* Solution
  * For each input box of submenus, add focus and blur event handler to generate `inputBoxEditingStarted` and `inputBoxEditingStoped` events to determine whether the color(hex) value is being edited or not.
  * The events in the submenu are received by the ui and re-fire, and the events are received in the imageEditor to know if the input box of the color picker is being editted.

---

Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: apps/image-editor/src/js/ui/text.js [hunk 1]
```diff
@@ -253,3 +275,5 @@ export default class Text extends Submenu {
     });
   }
 }
+
+export default Text;
```
Comment (jung-han) [inline apps/image-editor/src/js/ui/text.js:279]: 분리한 이유가 있을까요?

File: apps/image-editor/src/js/consts.js [hunk 2]
```diff
@@ -169,6 +169,18 @@ export const eventNames = {
...
+  FOCUS: 'focus',
+  BLUR: 'blur',
+};
+
+/**
+ * Selector names
+ * @type {Object.<string, string>}
+ */
+export const selectorNames = {
+  COLOR_PICKER_INPUT_BOX: '.tui-colorpicker-palette-hex',
```
Comment (jung-han) [inline apps/image-editor/src/js/consts.js:183]: 저희 요소니까 그냥 ID를 부여하는건 어떤가요?_?

**Review by dotaitch — APPROVED** [review]
리뷰 완료합니다.

File: apps/image-editor/src/js/consts.js (hunk 2 above)
Comment (lja1018) [reply apps/image-editor/src/js/consts.js:183]: `tui-color-picker`를 사용해서 일단 이대로 유지하겠습니다

File: apps/image-editor/src/js/ui/text.js (hunk 1 above)
Comment (lja1018) [reply apps/image-editor/src/js/ui/text.js:279]: 다른 작업하면서 분리했는데 다른 ui 컴포넌트들은 분리되어있고 Text만 합쳐져있어서 다른 ui 컴포넌트들과 맞춰주었습니다.
