### PR TITLE
fix: Do not send GA when 'usageStatistics: false' (fix #220)

### LINKED ISSUE #220: Propagete usageStatistics flag to colorPicker
## Version
v3.5.2

## Development Environment
various: Windows, Linux, MacOS
Chrome, Firefox

## Current Behavior
The colorPicker component trigger GA calls despite of the image-editor's flag `usageStatistics` has been set to `false`.

This induces a privacy issue

```js
// Probably some more options should be in src/js/ui/tools/colorpicker.js

this.picker = tuiColorPicker.create({
            container: this.pickerElement,
            preset: PICKER_COLOR,
            color: defaultColor
        });

```

## Expected Behavior
If the very top component's `usageStatistics` flag is set to a certain value, especially `false`, sub-components should take that into account by also setting their `usageStatistics` flag to the same value.

### PR DESCRIPTION
**Pull request by junghwan-park**
### Please check if the PR fulfills these requirements
- [x] It's submitted to right branch according to our branching model
- [x] It's right issue type on title
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `fix #xxx[,#xxx]`, where "xxx" is the issue number)
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes/features)
- [ ] Docs have been added/updated (for bug fixes/features)
- [x] It does not introduce a breaking change or has description for the breaking change

### Description

fixes #220

---
Thank you for your contribution to TOAST UI product. 🎉 😘 ✨

### CODE REVIEW

File: src/js/imageEditor.js [hunk 1]
```diff
@@ -78,6 +78,12 @@ class ImageEditor {
             usageStatistics: true
         }, options);
 
+        if (options.usageStatistics) {
+            sendHostName();
+        } else {
+            tui.usageStatistics = false;
```
Comment (jinwoo-kim-nhn) [inline src/js/imageEditor.js]: 갑자기 헷갈리는데.. node 모듈로 import 해서 사용하는 경우는 tui가 없을수도 있지 않을까요?
아래 아래처럼 해줘야 할것 같은 생각이 들어요
```js
if (!tui) {
  window.tui = {}; 
}
```

Comment (junghwan-park) [reply src/js/imageEditor.js]: 넵 이 부분은 스크럼에서 논의한 대로, 생성자에서 받은 옵션을 넘겨서 수정할 예정입니다! 감사합니다.
